create table tb_genre (
   id bigint generated by default as identity,
	name varchar(255),
	primary key (id)
);

create table tb_movie (
   id bigint generated by default as identity,
	img_url varchar(255),
	sub_title varchar(255),
	synopsis text,
	title varchar(255),
	year integer,
	genre_id bigint,
	primary key (id)
);

create table tb_review (
   id bigint generated by default as identity,
	text varchar(255),
	movie_id bigint,
	user_id bigint,
	primary key (id)
);

create table tb_role (
   id bigint generated by default as identity,
	authority varchar(255),
	primary key (id)
);

create table tb_user (
   id bigint generated by default as identity,
	email varchar(255),
	name varchar(255),
	password varchar(255),
	primary key (id)
);

create table tb_user_role (
   user_id bigint not null,
	role_id bigint not null,
	primary key (user_id, role_id)
);

alter table tb_movie 
   add constraint FKsgjdq7d9ajnr85pl4am109qsh 
   foreign key (genre_id) 
   references tb_genre;

alter table tb_review 
   add constraint FKmnmhbadmg8ugakn8q89rh5k3l 
   foreign key (movie_id) 
   references tb_movie;

alter table tb_review 
   add constraint FKqeh83gbufxg1ft0ubwn7w0tty 
   foreign key (user_id) 
   references tb_user;

alter table tb_user_role 
   add constraint FKea2ootw6b6bb0xt3ptl28bymv 
   foreign key (role_id) 
   references tb_role;

alter table tb_user_role 
   add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
   foreign key (user_id) 
   references tb_user;

